### ISSUE TITLE
Top-level meta annotation doesn't work

### ISSUE THREAD

**Issue by io7m** [immutables/immutables-javaslang#1]
The sources currently contain an annotation that attempts to aggregate the other annotations:

https://github.com/immutables/immutables-javaslang/blob/develop/immutables-javaslang-encodings/src/main/java/org/immutables/javaslang/encodings/JavaslangEncodingEnabled.java

Unfortunately, when applied directly to a type:

https://github.com/immutables/immutables-javaslang/blob/develop/immutables-javaslang-examples/src/main/java/org/immutables/javaslang/examples/ExampleMiscellaneousType.java

... nothing happens! The type does not behave as if it was annotated with all the constituent annotations.

@elucash: Any idea what's going on here? Perhaps I misunderstood what you meant by meta annotation.

**Comment by elucash** [comment]
sometimes I have something in mind about how it should work, but in reality, it could be not yet implemented that way. I'll check if it is fully implemented.

**Comment by elucash** [comment]
Looking thru code, while not the final conclusion, but can you try to also put `Style` annotation on that meta-annotated annotation just to see if it will change anything in that regard?

**Comment by io7m** [comment]
I added this:

```
--- a/immutables-javaslang-encodings/src/main/java/org/immutables/javaslang/encodings/JavaslangEncodingEnabled.java
+++ b/immutables-javaslang-encodings/src/main/java/org/immutables/javaslang/encodings/JavaslangEncodingEnabled.java
@@ -16,10 +16,13 @@
 
 package org.immutables.javaslang.encodings;
 
+import org.immutables.value.Value;
+
 /**
  * The top level meta annotation.
  */
 
+@Value.Style
 @JavaslangArrayEncodingEnabled
 @JavaslangCharSeqEncodingEnabled
 @JavaslangHashMapEncodingEnabled

```

... but it didn't seem to have any effect.

**Comment by io7m** [comment]
I'll try pushing a preliminary release to Central when https://github.com/immutables/immutables/issues/499 makes it into a release.

**Comment by elucash** [comment]
I'm finishing some last-minute fixes that our users reported and feasible to fix quickly, I'm planning to release it on Saturday or Sunday.
