### ISSUE TITLE
Multimap needs proper support

### ISSUE THREAD

**Issue by cozycode** [immutables/immutables-javaslang#6]
Multimaps aren't creating "add" methods in the builder.

PS: Thanks for creating immutables-javaslang(vavr)

**Comment by elucash** [comment]
Are there `put*` methods? IIRC there `add*` prefixes are not used for multimap initializers

**Comment by io7m** [comment]
> Are there put* methods? IIRC there add* prefixes are not used for multimap initializers

It seems that there are. I'll try to get this fixed shortly.

**Comment by io7m** [comment]
It was actually just a missing encoding.

@cozycode: Can you build the latest `develop` from source? If the added encoding works sufficiently well, I'll push a new release.

**Comment by cozycode** [comment]
That worked great. Thanks.
